---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: >
      (?x)^(
        examples/playbooks/(with-skip-tag-id|unicode).yml|
        examples/playbooks/example.yml
      )$
  - id: mixed-line-ending
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
    language_version: python3
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v2.2.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
